### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by 0xcircuitbreaker** [vikyd/go-checksum#3]
On any command I get this as a return

```go-checksum: command not found```

I have installed the go-checksum using the commands within the readme.

**Comment by vikyd** [comment]
Is $GOPATH/bin &nbsp;in your $PATH?




------------------ Original ------------------

**Comment by 0xcircuitbreaker** [comment]
I have ```export PATH=$GOPATH/bin:$GOROOT/bin:$PATH ```  and ```export GOROOT=/usr/local/go ```

**Comment by vikyd** [comment]
Check $GOPATH/bin/go-checksum, if existing, try to use absolute path.

------------------ Original ------------------
